const data = {
  status: "success",
  items: [
    {
      id: 0,
      title: "Burger Vegana",
      price: 530,
      image: "https://i.ibb.co/5BLDYRR/burger.png",
      marca: "I'm Veggie",
      cantidad: 1,
    },
    {
      id: 18,
      title: "Nuggets Vegatarianos",
      price: 680,
      image: "https://i.ibb.co/yspMJbP/tofu.png",
      marca: "Epuyen",
      cantidad: 1,
    },
    {
      id: 1,
      title: "Fideos Integrales",
      price: 250,
      image: "https://i.ibb.co/S5XgHkn/integrales.jpg",
      marca: "Grun",
      cantidad: 1,
    },
    {
      id: 2,
      title: "Fideos Wakas",
      price: 370,
      image: "https://i.ibb.co/D9j2qhv/wakas.jpg",
      marca: "Wakas",
      cantidad: 1,
    },
    {
      id: 3,
      title: "Fideo Tirabuzon",
      price: 320,
      image: "https://i.ibb.co/r0Bd98j/tirabuzon.jpg",
      marca: "Grun",
      cantidad: 1,
    },
    {
      id: 4,
      title: "Fideos de arroz",
      price: 320,
      image: "https://i.ibb.co/vvFmVws/fideo.jpg",
      marca: "Soyarroz",
      cantidad: 1,
    },
    {
      id: 5,
      title: "Fideos Integrales",
      price: 405,
      image: "https://i.ibb.co/RY8xJm1/lilen.jpg",
      marca: "Lilen",
      cantidad: 1,
    },
    {
      id: 6,
      title: "Mozzarella Vegana",
      price: 680,
      image: "https://i.ibb.co/5nQZzwN/mozzavegan.jpg",
      marca: "Felices las vacas",
      cantidad: 1,
    },
    {
      id: 7,
      title: "Harina Orgánica",
      price: 230,
      image: "https://i.ibb.co/6WJZ9Xf/harinaorgan.jpg",
      marca: "Grun",
      cantidad: 1,
    },
    {
      id: 8,
      title: "Azúcar Mascabo",
      price: 190,
      image: "https://i.ibb.co/gjQY6gq/mascabo.jpg",
      marca: "BEEPURE",
      cantidad: 1,
    },
    {
      id: 9,
      title: "Tofu Vegano",
      price: 500,
      image: "https://i.ibb.co/BfVw9JV/tfu.png",
      marca: "Soyana",
      cantidad: 1,
    },
    {
      id: 10,
      title: "Alfajor Sin Culpa",
      price: 130,
      image: "https://i.ibb.co/4pZJY4h/sinculpa.jpg",
      marca: "Sin Culpa",
      cantidad: 1,
    },
    {
      id: 11,
      title: "Grisines Orgánicos",
      price: 310,
      image: 'https://i.ibb.co/3yPwnbY/grisines.jpg',
      marca: "Grun",
      cantidad: 1,
    },
    {
      id: 12,
      title: "Pasta de Mani",
      price: 500,
      image: "https://i.ibb.co/Pzh2gG9/mani-king.jpg",
      marca: "ManiKing",
      cantidad: 1,
    },
    {
      id: 13,
      title: "Mani con chocolate",
      price: 290,
      image: "https://i.ibb.co/ftX6GvD/manichoco.png",
      marca: "ManiKing",
      cantidad: 1,
    },
    {
      id: 14,
      title: "Leche Vegana",
      price: 410,
      image: "https://i.ibb.co/ZXrnkpV/notmilk.jpg",
      marca: "Not Milk",
      cantidad: 1,
    },
    {
      id: 15,
      title: "Mayonesa Vegana",
      price: 370,
      image: "https://i.ibb.co/bXGS1hr/notmayo.jpg",
      marca: "Not",
      cantidad: 1,
    },
    {
      id: 16,
      title: "Pan Lactal",
      price: 340,
      image: "https://i.ibb.co/986t2bn/pan.jpg",
      marca: "Katz",
      cantidad: 1,
    },
    {
      id: 17,
      title: "Alfajor Algarroba",
      price: 250,
      image: "https://i.ibb.co/RHcKSz8/alfajoralgarroba.png",
      marca: "Epuyen",
      cantidad: 1,
    },
  ],
};

export default data;
