const data = {
  items: [
    {
      id: 0,
      nombre: "Burger Vegana",
      precio: 1230,
      imagen: "https://i.ibb.co/5BLDYRR/burger.png",
      marca: "I'm Veggie",
      cantidad: 1,
    },
    {
      id: 18,
      nombre: "Nuggets Vegatarianos",
      precio: 1680,
      imagen: "https://i.ibb.co/yspMJbP/tofu.png",
      marca: "Epuyen",
      cantidad: 1,
    },
    {
      id: 1,
      nombre: "Fideos Integrales",
      precio: 1250,
      imagen: "https://i.ibb.co/S5XgHkn/integrales.jpg",
      marca: "Grun",
      cantidad: 1,
    },
    {
      id: 2,
      nombre: "Fideos Wakas",
      precio: 1370,
      imagen: "https://i.ibb.co/D9j2qhv/wakas.jpg",
      marca: "Wakas",
      cantidad: 1,
    },
    {
      id: 3,
      nombre: "Fideo Tirabuzon",
      precio: 1320,
      imagen: "https://i.ibb.co/r0Bd98j/tirabuzon.jpg",
      marca: "Grun",
      cantidad: 1,
    },
    {
      id: 4,
      nombre: "Fideos de arroz",
      precio: 1220,
      imagen: "https://i.ibb.co/vvFmVws/fideo.jpg",
      marca: "Soyarroz",
      cantidad: 1,
    },
    {
      id: 5,
      nombre: "Fideos Integrales",
      precio: 1405,
      imagen: "https://i.ibb.co/RY8xJm1/lilen.jpg",
      marca: "Lilen",
      cantidad: 1,
    },
    {
      id: 6,
      nombre: "Mozzarella Vegana",
      precio: 1680,
      imagen: "https://i.ibb.co/5nQZzwN/mozzavegan.jpg",
      marca: "Felices las vacas",
      cantidad: 1,
    },
    {
      id: 7,
      nombre: "Harina Orgánica",
      precio: 1230,
      imagen: "https://i.ibb.co/6WJZ9Xf/harinaorgan.jpg",
      marca: "Grun",
      cantidad: 1,
    },
    {
      id: 8,
      nombre: "Azúcar Mascabo",
      precio: 890,
      imagen: "https://i.ibb.co/gjQY6gq/mascabo.jpg",
      marca: "BEEPURE",
      cantidad: 1,
    },
    {
      id: 9,
      nombre: "Tofu Vegano",
      precio: 1800,
      imagen: "https://i.ibb.co/BfVw9JV/tfu.png",
      marca: "Soyana",
      cantidad: 1,
    },
    {
      id: 10,
      nombre: "Alfajor Sin Culpa",
      precio: 430,
      imagen: "https://i.ibb.co/4pZJY4h/sinculpa.jpg",
      marca: "Sin Culpa",
      cantidad: 1,
    },
    {
      id: 11,
      nombre: "Grisines Orgánicos",
      precio: 710,
      imagen: "https://i.ibb.co/3yPwnbY/grisines.jpg",
      marca: "Grun",
      cantidad: 1,
    },
    {
      id: 12,
      nombre: "Pasta de Mani",
      precio: 1400,
      imagen: "https://i.ibb.co/Pzh2gG9/mani-king.jpg",
      marca: "ManiKing",
      cantidad: 1,
    },
    {
      id: 13,
      nombre: "Mani con chocolate",
      precio: 990,
      imagen: "https://i.ibb.co/ftX6GvD/manichoco.png",
      marca: "ManiKing",
      cantidad: 1,
    },
    {
      id: 14,
      nombre: "Leche Vegana",
      precio: 910,
      imagen: "https://i.ibb.co/ZXrnkpV/notmilk.jpg",
      marca: "Not Milk",
      cantidad: 1,
    },
    {
      id: 15,
      nombre: "Mayonesa Vegana",
      precio: 870,
      imagen: "https://i.ibb.co/bXGS1hr/notmayo.jpg",
      marca: "Not",
      cantidad: 1,
    },
    {
      id: 16,
      nombre: "Pan Lactal",
      precio: 840,
      imagen: "https://i.ibb.co/986t2bn/pan.jpg",
      marca: "Katz",
      cantidad: 1,
    },
    {
      id: 17,
      nombre: "Alfajor Algarroba",
      precio: 650,
      imagen: "https://i.ibb.co/RHcKSz8/alfajoralgarroba.png",
      marca: "Epuyen",
      cantidad: 1,
    },
  ],
};

export default data;
